# Combine clouds

Combine clouds from different files and interpolate missing values.

## Prepare the notebook

In [1]:
import os
from glob import glob
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt

## Configure which years to fill in with satellite (GOES) data

In [2]:
satellite_years = np.arange(2012, 2018)

## Load human evaluations

In [3]:
clouds = pd.read_hdf('clouds_ctio_blanco.h5').set_index(['date', 'quarter'])
clouds.head()

                    sday  eday  month  year  clouds source
date       quarter
1975-01-01 1           1     2      1  1975       0   ctio
           2           1     2      1  1975       0   ctio
           3           1     2      1  1975       0   ctio
           4           1     2      1  1975       0   ctio
1975-01-02 1           2     3      1  1975       0   ctio

### Track cloud value source

In [4]:
clouds['simulated'] = False
clouds

                    sday  eday  month  year  clouds  source  simulated
date       quarter
1975-01-01 1           1     2      1  1975       0    ctio      False
           2           1     2      1  1975       0    ctio      False
           3           1     2      1  1975       0    ctio      False
           4           1     2      1  1975       0    ctio      False
1975-01-02 1           2     3      1  1975       0    ctio      False
...                  ...   ...    ...   ...     ...     ...        ...
2022-09-03 4           3     4      9  2022       0  blanco      False
2022-09-04 1           4     5      9  2022       0  blanco      False
           2           4     5      9  2022       0  blanco      False
           3           4     5      9  2022       0  blanco      False
           4           4     5      9  2022       0  blanco      False

[69652 rows x 7 columns]

### Read quarters known to be cloudy from satellite data

In [5]:
clouds.index.names

FrozenList(['date', 'quarter'])

In [6]:
for year in satellite_years:
    satellite_cloudy_fname = f'satellite_clouds_4corr2_{year}.txt'
    if os.path.exists(satellite_cloudy_fname):
        sat_index_names = ['year', 'month', 'sday', 'quarter']
        satellite_cloudy = pd.read_csv(satellite_cloudy_fname, sep="\t", index_col=sat_index_names)
        old_index_names = clouds.index.names
        clouds = clouds.reset_index().set_index(sat_index_names)
        clouds.loc[satellite_cloudy.index.values, 'clouds'] = satellite_cloudy.estimated_eighths
        clouds.loc[satellite_cloudy.index.values, 'source'] = 'satellite'
        clouds = clouds.reset_index().set_index(old_index_names)
    
clouds

                    year  month  sday  eday  clouds  source  simulated
date       quarter
1975-01-01 1        1975      1     1     2       0    ctio      False
           2        1975      1     1     2       0    ctio      False
           3        1975      1     1     2       0    ctio      False
           4        1975      1     1     2       0    ctio      False
1975-01-02 1        1975      1     2     3       0    ctio      False
...                  ...    ...   ...   ...     ...     ...        ...
2022-09-03 4        2022      9     3     4       0  blanco      False
2022-09-04 1        2022      9     4     5       0  blanco      False
           2        2022      9     4     5       0  blanco      False
           3        2022      9     4     5       0  blanco      False
           4        2022      9     4     5       0  blanco      False

[69652 rows x 7 columns]

In [7]:
satellite_cloudy

                         estimated_eighths  fraction_above_cloudcut
year month sday quarter
2017 1     1    1                        3                 0.597222
                2                        1                 0.888889
                3                        0                 1.000000
                4                        0                 1.000000
           5    1                        3                 0.576389
...                                    ...                      ...
     12    30   4                        0                 1.000000
           31   1                        2                 0.798611
                2                        0                 0.944444
                3                        0                 0.986111
                4                        1                 0.814815

[138 rows x 2 columns]

### Build a stochastic matrix

In [8]:
transitions = pd.DataFrame({'month': clouds.month[:-1].values, 'clouds': clouds.clouds[:-1].values, 'next_clouds': clouds.clouds[1:].values, 'count': 1})
transition_counts = transitions.groupby(['month', 'clouds', 'next_clouds']).count()

Remove transitions to and from missing data:

In [9]:
transition_counts = transition_counts.reset_index().query('(clouds != 9) and (next_clouds != 9)').set_index(['month', 'clouds', 'next_clouds'])

Reshape into a matrix:

In [10]:
transition_matrix = transition_counts.unstack().fillna(0)
transition_matrix

               count
next_clouds        0      1     2     3     4     5     6     7     8
month clouds
1     0       4167.0  140.0  51.0  50.0  24.0  17.0   6.0   3.0   7.0
      1        172.0  165.0  44.0  21.0  15.0   6.0   4.0   2.0   0.0
      2         50.0   82.0  70.0  28.0  19.0   3.0   3.0   1.0   2.0
      3         35.0   23.0  40.0  51.0  17.0  15.0   8.0   3.0   2.0
      4         21.0    9.0  30.0  28.0  34.0  11.0   5.0   6.0   4.0
...              ...    ...   ...   ...   ...   ...   ...   ...   ...
12    4         12.0    3.0  15.0  22.0  25.0  12.0  17.0   3.0   5.0
      5          8.0    4.0   7.0   5.0  15.0  21.0  12.0   6.0   2.0
      6         12.0    4.0   7.0   5.0   9.0   5.0  15.0   9.0  11.0
      7          6.0    0.0   2.0   0.0   3.0   5.0   7.0  13.0  13.0
      8         11.0    3.0   4.0   4.0   4.0   3.0   7.0  12.0  74.0

[108 rows x 9 columns]

In [11]:
def counts_to_freq(count_df):
    df = count_df.copy()
    df['sum'] = count_df.sum(axis=1)
    for col in df.columns:
        df[col] = df[col]/df['sum']
    df.drop(columns=['sum'], inplace=True)
    df.columns = df.columns.droplevel(0)
    return df

In [12]:
stoch_matrix = counts_to_freq(transition_matrix)
stoch_matrix

next_clouds          0         1         2         3         4         5  \
month clouds
1     0       0.933259  0.031355  0.011422  0.011198  0.005375  0.003807
      1       0.400932  0.384615  0.102564  0.048951  0.034965  0.013986
      2       0.193798  0.317829  0.271318  0.108527  0.073643  0.011628
      3       0.180412  0.118557  0.206186  0.262887  0.087629  0.077320
      4       0.141892  0.060811  0.202703  0.189189  0.229730  0.074324
...                ...       ...       ...       ...       ...       ...
12    4       0.105263  0.026316  0.131579  0.192982  0.219298  0.105263
      5       0.100000  0.050000  0.087500  0.062500  0.187500  0.262500
      6       0.155844  0.051948  0.090909  0.064935  0.116883  0.064935
      7       0.122449  0.000000  0.040816  0.000000  0.061224  0.102041
      8       0.090164  0.024590  0.032787  0.032787  0.032787  0.024590

next_clouds          6         7         8
month clouds
1     0       0.001344  0.000672  0.001568
      1       0.009324  0.004662  0.000000
      2       0.011628  0.003876  0.007752
      3       0.041237  0.015464  0.010309
      4       0.033784  0.040541  0.027027
...                ...       ...       ...
12    4       0.149123  0.026316  0.043860
      5       0.150000  0.075000  0.025000
      6       0.194805  0.116883  0.142857
      7       0.142857  0.265306  0.265306
      8       0.057377  0.098361  0.606557

[108 rows x 9 columns]

In [13]:
def simulate_clouds(clouds, seed=6563):
    random_number_generator = np.random.default_rng(seed)
    
    filled_clouds = clouds.copy()
    filled_clouds['simulated'] = False

    previous_quarter_clouds = clouds.clouds.shift(1)
    missing_clouds = clouds.query('clouds==9')
    for quarter, row in missing_clouds.iterrows():
        if previous_quarter_clouds[quarter] == 9:
            previous_clouds = previous_sim_clouds
        else:
            previous_clouds = previous_quarter_clouds[quarter]
        
        frequencies = stoch_matrix.loc[(row.month, previous_clouds), :]
        random_number = random_number_generator.random()
        filled_clouds.loc[quarter, 'clouds'] = frequencies[frequencies.cumsum() > random_number].index.min()
        filled_clouds.loc[quarter, 'source'] = 'stochastic_matrix'
        filled_clouds.loc[quarter, 'simulated'] = True
        previous_sim_clouds = filled_clouds.loc[quarter, 'clouds']
            
    return filled_clouds

In [14]:
filled_clouds = simulate_clouds(clouds)
filled_clouds

                    year  month  sday  eday  clouds  source  simulated
date       quarter
1975-01-01 1        1975      1     1     2       0    ctio      False
           2        1975      1     1     2       0    ctio      False
           3        1975      1     1     2       0    ctio      False
           4        1975      1     1     2       0    ctio      False
1975-01-02 1        1975      1     2     3       0    ctio      False
...                  ...    ...   ...   ...     ...     ...        ...
2022-09-03 4        2022      9     3     4       0  blanco      False
2022-09-04 1        2022      9     4     5       0  blanco      False
           2        2022      9     4     5       0  blanco      False
           3        2022      9     4     5       0  blanco      False
           4        2022      9     4     5       0  blanco      False

[69652 rows x 7 columns]

In [15]:
filled_clouds.to_hdf('clouds.h5', key='clouds')

In [16]:
filled_clouds.query('source == "satellite"')

                    year  month  sday  eday  clouds     source  simulated
date       quarter
2012-01-01 1        2012      1     1     2       8  satellite      False
           2        2012      1     1     2       7  satellite      False
           3        2012      1     1     2       6  satellite      False
2012-08-16 1        2012      8    16    17       8  satellite      False
           2        2012      8    16    17       7  satellite      False
...                  ...    ...   ...   ...     ...        ...        ...
2017-12-30 4        2017     12    30    31       0  satellite      False
2017-12-31 1        2017     12    31     1       2  satellite      False
           2        2017     12    31     1       0  satellite      False
           3        2017     12    31     1       0  satellite      False
           4        2017     12    31     1       1  satellite      False

[692 rows x 7 columns]